from distutils.core import setup

__version__ = '1.2.2'

setup(
    name = 'kunteksto',
  packages = ['kunteksto'],  
  version = '1.2.2',
  description = 'The Context tool for your data.',
  author = 'Timothy W. Cook',
  author_email = 'tim@datainsights.tech',
  url = 'https://github.com/DataInsightsInc/Kunteksto',  
  download_url = 'https://github.com/DataInsightsInc/Kunteksto/archive/1.2.2.tar.gz',  
  keywords = ['context', 'rdf', 'xml', 'machine learning', 'data-centric', 'semantic interoperability', 'semantics'], 
  classifiers = [],
  install_requires=[
      'agraph-python==6.1.5',
      'alabaster==0.7.10',
      'async-timeout==1.2.0',
      'Babel==2.4.0',
      'chardet==3.0.2',
      'Cython==0.25.2',
      'docutils==0.13.1',
      'future==0.16.0',
      'imagesize==0.7.1',
      'inflection==0.3.1',
      'iso8601==0.1.11',
      'Jinja2==2.9.6',
      'lxml==3.7.3',
      'MarkupSafe==1.0',
      'multidict==2.1.4',
      'pycurl==7.43.0',
      'Pygments==2.2.0',
      'pymongo==3.4.0',
      'pytz==2017.2',
      'PyYAML==3.12',
      'requests==2.13.0',
      'shortuuid==0.5.0',
      'six==1.10.0',
      'snowballstemmer==1.2.1',
      'Sphinx==1.5.5',
      'sphinx-rtd-theme==0.2.4',
      'ujson==1.35',
      'uvloop==0.8.0',
      'xmltodict==0.10.2',
      'yarl==0.9.8',
      'openssl',
      'readline',
      'sqlite',
      'tk',
      'zlib',      
      ],
)