from setuptools import setup

import configparser

config = configparser.ConfigParser()
config.read('kunteksto.conf')
VERSION = config['SYSTEM']['version']

setup(
    name = 'kunteksto',
    version = VERSION,
    description = 'The Context tool for your data. This is your tool to enter the emerging datacentric, model-based approach to information management. ',
    long_description = """Kunteksto (ˈkänˌteksto) is a tool to help domain experts, data creators and data users translate their simple CSV formatted data files into the semantically enhanced formats that provide computable metadata. 
    This provides a path for existing data to be used in conjuntion with the emerging *datacentric, model based* approach in analysis, general artificial intelligence and decision support systems. 
    This approach opens the door for the change to a *datacentric* world as opposed to the *application-centric* one we have now. 
    This new approach enables automatic interoperability avoiding the data quality issues created through data cleaning and massaging. The importance of this capability and improved data quality 
    is discussed in foundational `S3Model <https://datainsights.tech/S3Model>`_ documentation and references. However, detailed understanding of S3Model is not required to understand and use 
    the power of Kunteksto. The next step for enterprise environments is creating reusable components with the `Datacentric Tool Suite <https://datainsights.tech/datacentrictools/>`_
""",
    author = 'Timothy W. Cook',
    author_email = 'tim@datainsights.tech',
    url = 'https://datainsights.tech/Kunteksto/',  
    download_url = 'https://github.com/DataInsightsInc/Kunteksto/archive/' + VERSION + '.tar.gz',  
    keywords = ['context rdf xml machine learning data-centric semantic interoperability semantics'], 
    tests_require=['pytest',],  
    setup_requires=['pytest-runner',],  
    python_requires='>=3.6',
    packages=['kunteksto'],
    package_dir={'kunteksto': 'kunteksto'},
    package_data={'docs': ['docs/*']},
    data_files=[('example_data', ['example_data/Demo.csv','example_data/Demo2.csv','example_data/Demo3.csv','example_data/Demo_info.pdf']),
                ('s3model', ['s3model/s3model_3_1_0.xsl','s3model/s3model_3_1_0.xsd','s3model/s3model_3_1_0.rdf','s3model/s3model.owl','s3model/dm-description.xsl']),
                ('output', ['output/dm-description.xsl']),('catalogs',['catalogs/Kunteksto_catalog.xml']),('',['kunteksto.conf','README.md','LICENSE.txt']),('utils',['utils/allegro_test.py','utils/db_setup;py'])],
    install_requires=[
        'agraph-python==100.1.1',
        'alabaster==0.7.10',
        'asn1crypto==0.24.0',
        'attrs==18.1.0',
        'async-timeout==1.2.0',
        'babel==2.5.3',
        'basexclient==8.4.4',
        'ca-certificates==2018.03.07',
        'certifi==2018.4.16',
        'cffi==1.11.',
        'chardet==3.0.4',
        'click==6.7',
        'cryptography==2.2.2',
        'curl==7.59.0',
        'cython==0.28.2',
        'docutils==0.14',
        'future==0.16.0',
        'icu==58.2',
        'idna==2.6',
        'imagesize==1.0.0',
        'inflection==0.3.1',
        'iso8601==0.1.12',
        'jinja2==2.10',
        'libcurl==7.59.0',
        'lxml==3.8.0',
        'libedit==3.1.20170329',
        'libffi==3.2.1',
        'libgcc-ng==7.2.0',
        'libssh2==1.8.0',
        'libstdcxx-ng==7.2.0',
        'libxml2==2.9.8',
        'libxslt==1.1.32',
        'lxml==4.2.1',
        'markupsafe==1.0',
        'more-itertools==4.1.0',
        'multidict==2.1.4',
        'ncurses==6.1',
        'openssl==1.0.2o',
        'pip==10.0.1',
        'pkginfo==1.4.2',
        'pluggy==0.6.0',
        'pycodestyle==2.4.0',
        'pycparser==2.18',
        'pycurl==7.43.0.1',
        'pygments==2.2.0',
        'pymongo==3.4.0',
        'pyopenssl==18.0.0',
        'pysocks==1.6.8',
        'pytest==3.5.1'
        'pytz==2018.4',
        'pyyaml==3.12',
        'readline==7.0',
        'requests==2.18.4',
        'setuptools==39.1.0',
        'shortuuid==0.5.0',
        'six==1.11.0',
        'snowballstemmer==1.2.1',
        'sphinx==1.5.5',
        'sphinx-rtd-theme==0.2.4',
        'sqlite==3.23.1',
        'tk==8.6.7',
        'tqdm==4.23.0',
        'typing==3.6.4',
        'ujson==1.35',
        'urllib3==1.22',
        'wheel==0.31.1',
        'xz==5.2.4',
        'yaml==0.1.7',
        'xmltodict==0.10.2',
        'yarl==0.9.8',
        'zlib==1.2.11'
      ],
    entry_points='''
            [console_scripts]
            kunteksto=kunteksto.kunteksto:main
        ''',    
    classifiers = ['Development Status :: 5 - Production/Stable',
                   'Intended Audience :: Customer Service',
                   'Intended Audience :: Developers',
                   'Intended Audience :: Education',
                   'Intended Audience :: End Users/Desktop',
                   'Intended Audience :: Financial and Insurance Industry',
                   'Intended Audience :: Healthcare Industry',
                   'Intended Audience :: Information Technology',
                   'Intended Audience :: Legal Industry',
                   'Intended Audience :: Manufacturing',
                   'Intended Audience :: Other Audience',
                   'Intended Audience :: Religion',
                   'Intended Audience :: Science/Research',
                   'Intended Audience :: System Administrators',
                   'Intended Audience :: Telecommunications Industry',
                   'License :: OSI Approved :: Apache Software License',
                   'Programming Language :: Python :: 3 :: Only',
                   'Topic :: Scientific/Engineering :: Information Analysis',
                   ],

)